# -*- coding: utf-8 -*-
"""AI Game Referee – Rock–Paper–Scissors–Plus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tf_DI9086iUSGnCTOruUYIBaG1AXR78i
"""

import random

game_state = {
    "round": 1,
    "max_rounds": 3,
    "user_score": 0,
    "bot_score": 0,
    "user_bomb_used": False,
    "bot_bomb_used": False,
    "history": []
}

def parse_intent(user_input: str):
    user_input = user_input.strip().lower()

    if user_input in ["rock", "paper", "scissors", "bomb"]:
        return {
            "intent": "play_move",
            "move": user_input
        }
    return {
        "intent": "invalid_input",
        "move": None
    }

def validate_move(intent_data, state):
    if intent_data["intent"] != "play_move":
        return {
            "valid": False,
            "reason": "Invalid input"
        }
    move = intent_data["move"]
    if move == "bomb" and state["user_bomb_used"]:
        return {
            "valid": False,
            "reason": "Bomb already used"
        }
    return {
        "valid": True,
        "move": move
    }

def choose_bot_move(state):
    moves = ["rock", "paper", "scissors"]
    if not state["bot_bomb_used"]:
        moves.append("bomb")
    return random.choice(moves)

def resolve_round(user_move, bot_move):
    if user_move == bot_move:
        return "draw"
    if user_move == "bomb" and bot_move == "bomb":
        return "draw"
    if user_move == "bomb":
        return "user"
    if bot_move == "bomb":
        return "bot"
    rules = {
        "rock": "scissors",
        "scissors": "paper",
        "paper": "rock"
    }
    return "user" if rules[user_move] == bot_move else "bot"

def update_game_state(state, user_move, bot_move, result):
    if user_move == "bomb":
        state["user_bomb_used"] = True
    if bot_move == "bomb":
        state["bot_bomb_used"] = True
    if result == "user":
        state["user_score"] += 1
    elif result == "bot":
        state["bot_score"] += 1
    state["history"].append({
        "round": state["round"],
        "user_move": user_move,
        "bot_move": bot_move,
        "winner": result
    })
    state["round"] += 1

print("Welcome to Rock–Paper–Scissors–Plus!")
print("Rules:")
print("• Best of 3 rounds")
print("• Moves: rock, paper, scissors, bomb (once)")
print("• Bomb beats everything; invalid move wastes the round")
print("-" * 50)

while game_state["round"] <= game_state["max_rounds"]:
    print(f"\nRound {game_state['round']}")
    user_input = input("Enter your move: ")
    intent = parse_intent(user_input)
    validation = validate_move(intent, game_state)
    if not validation["valid"]:
        print(f"Invalid move: {validation['reason']}")
        print("Round wasted.")
        update_game_state(game_state, "invalid", "none", "draw")
        continue
    user_move = validation["move"]
    bot_move = choose_bot_move(game_state)

    result = resolve_round(user_move, bot_move)
    update_game_state(game_state, user_move, bot_move, result)
    print(f"You played: {user_move}")
    print(f"Bot played: {bot_move}")

    if result == "user":
        print("Winner: You")
    elif result == "bot":
        print("Winner: Bot")
    else:
        print("Result: Draw")

    print(f"Score → You: {game_state['user_score']} | Bot: {game_state['bot_score']}")

print("\nGame Over!")
print(f"Final Score → You: {game_state['user_score']} | Bot: {game_state['bot_score']}")
if game_state["user_score"] > game_state["bot_score"]:
    print("Final Result: You win ")
elif game_state["user_score"] < game_state["bot_score"]:
    print("Final Result: Bot wins ")
else:
    print("Final Result: Draw")